DepoOdevi/DepoOdevi/Controllers/EmployeeController.cs
using Business.Concrete;
using Data.Concrete;
using Data.EntityFramework;
using Entity.Concrete;
using System;
using System.Web.Mvc;

namespace UI.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly EmployeeManager _employeeManager;

        public EmployeeController()
        {
            _employeeManager = new EmployeeManager(new EfEmployeeDal());
        }

        public ActionResult Index()
        {
            var employees = _employeeManager.GetList();
            return View(employees);
        }

        public ActionResult Details(int id)
        {
            var employee = _employeeManager.GetById(id);
            return View(employee);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                employee.StartDate = DateTime.Now;
                _employeeManager.EmployeeAdd(employee);
                return RedirectToAction("Index");
            }

            return View(employee);
        }

        public ActionResult Edit(int id)
        {
            var employee = _employeeManager.GetById(id);
            return View(employee);
        }

        [HttpPost]
        public ActionResult Edit(Employee employee)
        {
            if (ModelState.IsValid)
            {
                _employeeManager.EmployeeUpdate(employee);
                return RedirectToAction("Index");
            }
            return View(employee);
        }
        public ActionResult Delete(int id)
        {
            var employee = _employeeManager.GetById(id);
            return View(employee);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var employee = _employeeManager.GetById(id);
            _employeeManager.EmployeeDelete(employee);
            return RedirectToAction("Index");
        }
    }
}

DepoOdevi/DepoOdevi/Controllers/ProductController.cs
using Business.Concrete;
using Data.Concrete;
using Data.EntityFramework;
using Entity.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DepoUI.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductManager productManager;
        private readonly CategoryManager categoryManager;
        private readonly SupplierManager supplierManager;
        private readonly StockMovementManager stockMovementManager;
        private readonly EmployeeManager employeeManager;

        public ProductController()
        {
            productManager = new ProductManager(new EfProductDal());
            categoryManager = new CategoryManager(new EfCategoryDal());
            supplierManager = new SupplierManager(new EfSupplierDal());
            stockMovementManager = new StockMovementManager(new EfStockMovementDal());
            employeeManager = new EmployeeManager(new EfEmployeeDal());
        }

        public ActionResult Index()
        {
            var productValues = productManager.GetProductsWithDetails();
            return View(productValues);
        }

        public ActionResult Details(int id)
        {
            var productValue = productManager.GetById(id);
            return View(productValue);
        }

        public ActionResult Create()
        {
            PopulateDropdownLists();
            return View();
        }

        [HttpPost]
        public ActionResult Create(Product product)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    productManager.ProductAdd(product);
                    return RedirectToAction("Index");
                }

                PopulateDropdownLists();
                return View(product);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Hata oluştu: " + ex.Message);
                PopulateDropdownLists();
                return View(product);
            }
        }

        public ActionResult Edit(int id)
        {
            PopulateDropdownLists();
            var productValue = productManager.GetById(id);
            return View(productValue);
        }

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    productManager.ProductUpdate(product);
                    return RedirectToAction("Index");
                }

                PopulateDropdownLists();
                return View(product);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Hata oluştu: " + ex.Message);
                PopulateDropdownLists();
                return View(product);
            }
        }

        public ActionResult Delete(int id)
        {
            var productValue = productManager.GetById(id);
            return View(productValue);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                var product = productManager.GetById(id);
                productManager.ProductDelete(product);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Hata oluştu: " + ex.Message);
                return View(productManager.GetById(id));
            }
        }

  

        
        public ActionResult StockCount()
        {
            var products = productManager.GetList();
            ViewBag.EmployeeList = employeeManager.GetList()
                .Select(x => new SelectListItem
                {
                    Text = x.FirstName + " " + x.LastName,
                    Value = x.EmployeeId.ToString()
                }).ToList();
            return View(products);
        }
        
        [HttpPost]
        public ActionResult StockCount(FormCollection form)
        {
            try
            {
                int employeeId = Convert.ToInt32(form["EmployeeId"]);
                string description = form["Description"] ?? "Stok Sayımı";
                
                foreach (var key in form.AllKeys)
                {
                    if (key.StartsWith("count_"))
                    {
                        int productId = Convert.ToInt32(key.Replace("count_", ""));
                        int newCount = Convert.ToInt32(form[key]);
                        
                        var product = productManager.GetById(productId);
                        if (product != null)
                        {
                            var stockMovement = new StockMovement
                            {
                                ProductId = productId,
                                EmployeeId = employeeId,
                                Quantity = newCount,
                                MovementType = "Sayım",
                                MovementDate = DateTime.Now,
                                Description = description
                            };
                            
                            stockMovementManager.StockMovementAdd(stockMovement);
                        }
                    }
                }
                
                TempData["Message"] = "Stok sayımı başarıyla tamamlandı.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["Error"] = "Hata oluştu: " + ex.Message;
                return RedirectToAction("StockCount");
            }
        }

        private void PopulateDropdownLists()
        {
            ViewBag.CategoryList = categoryManager.GetList()
                .Select(x => new SelectListItem
                {
                    Text = x.CategoryName,
                    Value = x.CategoryId.ToString()
                }).ToList();

            ViewBag.SupplierList = supplierManager.GetList()
                .Select(x => new SelectListItem
                {
                    Text = x.CompanyName,
                    Value = x.SupplierId.ToString()
                }).ToList();
        }
    }
}

DepoOdevi/DepoOdevi/Controllers/StockMovementController.cs
using Business.Concrete;
using Data.Concrete;
using Data.EntityFramework;
using Entity.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace UI.Controllers
{
    public class StockMovementController : Controller
    {
        private readonly StockMovementManager _stockMovementManager;
        private readonly ProductManager _productManager;
        private readonly EmployeeManager _employeeManager;

        public StockMovementController()
        {
            _stockMovementManager = new StockMovementManager(new EfStockMovementDal());
            _productManager = new ProductManager(new EfProductDal());
            _employeeManager = new EmployeeManager(new EfEmployeeDal());
        }

        // GET: StockMovement
        public ActionResult Index()
        {
            var stockMovements = _stockMovementManager.GetList();
            return View(stockMovements);
        }

        // GET: StockMovement/Details/5
        public ActionResult Details(int id)
        {
            var stockMovement = _stockMovementManager.GetById(id);
            return View(stockMovement);
        }

        // GET: StockMovement/Create
        public ActionResult Create()
        {
            ViewBag.ProductId = new SelectList(_productManager.GetList(), "ProductId", "ProductName");
            ViewBag.EmployeeId = new SelectList(_employeeManager.GetList(), "EmployeeId", "FirstName");
            ViewBag.MovementTypes = new List<SelectListItem>
            {
                new SelectListItem { Text = "Giriş", Value = "Giriş" },
                new SelectListItem { Text = "Çıkış", Value = "Çıkış" },
                new SelectListItem { Text = "Sayım", Value = "Sayım" },
                new SelectListItem { Text = "Satış", Value = "Satış" },
                new SelectListItem { Text = "İade", Value = "İade" }
            };

            return View();
        }

        // POST: StockMovement/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StockMovement stockMovement)
        {
            if (ModelState.IsValid)
            {
                stockMovement.MovementDate = DateTime.Now;
                _stockMovementManager.StockMovementAdd(stockMovement);
                return RedirectToAction("Index");
            }

            ViewBag.ProductId = new SelectList(_productManager.GetList(), "ProductId", "ProductName", stockMovement.ProductId);
            ViewBag.EmployeeId = new SelectList(_employeeManager.GetList(), "EmployeeId", "FirstName", stockMovement.EmployeeId);
            ViewBag.MovementTypes = new List<SelectListItem>
            {
                new SelectListItem { Text = "Giriş", Value = "Giriş", Selected = stockMovement.MovementType == "Giriş" },
                new SelectListItem { Text = "Çıkış", Value = "Çıkış", Selected = stockMovement.MovementType == "Çıkış" },
                new SelectListItem { Text = "Sayım", Value = "Sayım", Selected = stockMovement.MovementType == "Sayım" },
                new SelectListItem { Text = "Satış", Value = "Satış", Selected = stockMovement.MovementType == "Satış" },
                new SelectListItem { Text = "İade", Value = "İade", Selected = stockMovement.MovementType == "İade" }
            };

            return View(stockMovement);
        }

        // GET: StockMovement/Edit/5
        public ActionResult Edit(int id)
        {
            var stockMovement = _stockMovementManager.GetById(id);

            ViewBag.ProductId = new SelectList(_productManager.GetList(), "ProductId", "ProductName", stockMovement.ProductId);
            ViewBag.EmployeeId = new SelectList(_employeeManager.GetList(), "EmployeeId", "FirstName", stockMovement.EmployeeId);
            ViewBag.MovementTypes = new List<SelectListItem>
            {
                new SelectListItem { Text = "Giriş", Value = "Giriş", Selected = stockMovement.MovementType == "Giriş" },
                new SelectListItem { Text = "Çıkış", Value = "Çıkış", Selected = stockMovement.MovementType == "Çıkış" },
                new SelectListItem { Text = "Sayım", Value = "Sayım", Selected = stockMovement.MovementType == "Sayım" },
                new SelectListItem { Text = "Satış", Value = "Satış", Selected = stockMovement.MovementType == "Satış" },
                new SelectListItem { Text = "İade", Value = "İade", Selected = stockMovement.MovementType == "İade" }
            };

            return View(stockMovement);
        }

        // POST: StockMovement/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(StockMovement stockMovement)
        {
            if (ModelState.IsValid)
            {
                _stockMovementManager.StockMovementUpdate(stockMovement);
                return RedirectToAction("Index");
            }

            ViewBag.ProductId = new SelectList(_productManager.GetList(), "ProductId", "ProductName", stockMovement.ProductId);
            ViewBag.EmployeeId = new SelectList(_employeeManager.GetList(), "EmployeeId", "FirstName", stockMovement.EmployeeId);
            ViewBag.MovementTypes = new List<SelectListItem>
            {
                new SelectListItem { Text = "Giriş", Value = "Giriş", Selected = stockMovement.MovementType == "Giriş" },
                new SelectListItem { Text = "Çıkış", Value = "Çıkış", Selected = stockMovement.MovementType == "Çıkış" },
                new SelectListItem { Text = "Sayım", Value = "Sayım", Selected = stockMovement.MovementType == "Sayım" },
                new SelectListItem { Text = "Satış", Value = "Satış", Selected = stockMovement.MovementType == "Satış" },
                new SelectListItem { Text = "İade", Value = "İade", Selected = stockMovement.MovementType == "İade" }
            };

            return View(stockMovement);
        }

        // GET: StockMovement/Delete/5
        public ActionResult Delete(int id)
        {
            var stockMovement = _stockMovementManager.GetById(id);
            return View(stockMovement);
        }

        // POST: StockMovement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var stockMovement = _stockMovementManager.GetById(id);
            _stockMovementManager.StockMovementDelete(stockMovement);
            return RedirectToAction("Index");
        }

        // GET: StockMovement/ProductStock/5
        public ActionResult ProductStock(int id)
        {
            var product = _productManager.GetById(id);
            ViewBag.Product = product;
            ViewBag.CurrentStock = _stockMovementManager.GetProductCurrentStock(id);
            var movements = _stockMovementManager.GetStockMovementsByProduct(id);
            return View(movements);
        }

        // GET: StockMovement/EmployeeMovements/5
        public ActionResult EmployeeMovements(int id)
        {
            var employee = _employeeManager.GetById(id);
            ViewBag.Employee = employee;
            var movements = _stockMovementManager.GetStockMovementsByEmployee(id);
            return View(movements);
        }
    }
}

DepoOdevi/DepoOdevi/Views/StockMovement/EmployeeMovements.cshtml
@model IEnumerable<Entity.Concrete.StockMovement>
@{
    ViewBag.Title = "Çalışan Stok Hareketleri";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var employee = ViewBag.Employee as Entity.Concrete.Employee;
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">@($"{employee.FirstName} {employee.LastName}") - Stok Hareketleri</h3>
        <div class="card-tools">
            <a href="@Url.Action("Details", "Employee", new { id = employee.EmployeeId })" class="btn btn-secondary btn-sm">
                <i class="fas fa-arrow-left"></i> Çalışan Detayına Dön
            </a>
            <a href="@Url.Action("Create", "StockMovement")" class="btn btn-primary btn-sm">
                <i class="fas fa-plus"></i> Yeni Stok Hareketi
            </a>
        </div>
    </div>
    <div class="card-body">
        <div class="row mb-4">
            <div class="col-md-3">
                <div class="card bg-info text-white">
                    <div class="card-body">
                        <h5 class="card-title">Toplam Hareket</h5>
                        <h2>@Model.Count()</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card bg-success text-white">
                    <div class="card-body">
                        <h5 class="card-title">Giriş Hareketleri</h5>
                        <h2>@Model.Count(m => m.MovementType == "Giriş")</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card bg-danger text-white">
                    <div class="card-body">
                        <h5 class="card-title">Çıkış Hareketleri</h5>
                        <h2>@Model.Count(m => m.MovementType == "Çıkış")</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card bg-primary text-white">
                    <div class="card-body">
                        <h5 class="card-title">Satış Hareketleri</h5>
                        <h2>@Model.Count(m => m.MovementType == "Satış")</h2>
                    </div>
                </div>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-light">
                        <h5 class="card-title">Çalışan Bilgileri</h5>
                    </div>
                    <div class="card-body">
                        <p><strong>Ad Soyad:</strong> @($"{employee.FirstName} {employee.LastName}")</p>
                        <p><strong>Görev:</strong> @employee.Task</p>
                        <p><strong>Telefon:</strong> @employee.Phone</p>
                        <p><strong>E-posta:</strong> @employee.Mail</p>
                        <p><strong>Başlangıç Tarihi:</strong> @employee.StartDate.ToString("dd/MM/yyyy")</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-light">
                        <h5 class="card-title">Hareket Özeti</h5>
                    </div>
                    <div class="card-body">
                        <p><strong>Toplam Giriş Miktarı:</strong> @Model.Where(m => m.MovementType == "Giriş").Sum(m => m.Quantity)</p>
                        <p><strong>Toplam Çıkış Miktarı:</strong> @Model.Where(m => m.MovementType == "Çıkış").Sum(m => m.Quantity)</p>
                        <p><strong>Toplam Satış Miktarı:</strong> @Model.Where(m => m.MovementType == "Satış").Sum(m => m.Quantity)</p>
                        <p><strong>Toplam İade Miktarı:</strong> @Model.Where(m => m.MovementType == "İade").Sum(m => m.Quantity)</p>
                        <p><strong>Toplam Sayım Miktarı:</strong> @Model.Where(m => m.MovementType == "Sayım").Sum(m => m.Quantity)</p>
                    </div>
                </div>
            </div>
        </div>

        <h4 class="mt-4">Stok Hareketleri</h4>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Ürün</th>
                    <th>Hareket Tipi</th>
                    <th>Miktar</th>
                    <th>Birim Fiyat</th>
                    <th>Tarih</th>
                    <th>Açıklama</th>
                    <th>İşlemler</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.OrderByDescending(m => m.MovementDate))
                {
                    <tr>
                        <td>@item.Product.ProductName</td>
                        <td>
                            @if (item.MovementType == "Giriş")
                            {
                                <span class="badge bg-success">@item.MovementType</span>
                            }
                            else if (item.MovementType == "Çıkış")
                            {
                                <span class="badge bg-danger">@item.MovementType</span>
                            }
                            else if (item.MovementType == "Sayım")
                            {
                                <span class="badge bg-info">@item.MovementType</span>
                            }
                            else if (item.MovementType == "Satış")
                            {
                                <span class="badge bg-primary">@item.MovementType</span>
                            }
                            else if (item.MovementType == "İade")
                            {
                                <span class="badge bg-warning">@item.MovementType</span>
                            }
                            else
                            {
                                <span class="badge bg-secondary">@item.MovementType</span>
                            }
                        </td>
                        <td>@item.Quantity</td>
                        <td>@(item.UnitPrice.HasValue ? string.Format("{0:C2}", item.UnitPrice) : "-")</td>
                        <td>@item.MovementDate.ToString("dd/MM/yyyy HH:mm")</td>
                        <td>@(string.IsNullOrEmpty(item.Description) ? "-" : item.Description)</td>
                        <td>
                            <a href="@Url.Action("Details", "StockMovement", new { id = item.StockMovementId })" class="btn btn-primary btn-sm">
                                <i class="fas fa-search"></i> Detay
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div> 

DepoOdevi/DepoOdevi/Views/StockMovement/ProductStock.cshtml
@model IEnumerable<Entity.Concrete.StockMovement>
@{
    ViewBag.Title = "Ürün Stok Hareketleri";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var product = ViewBag.Product as Entity.Concrete.Product;
    var currentStock = ViewBag.CurrentStock;
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">@product.ProductName - Stok Hareketleri</h3>
        <div class="card-tools">
            <a href="@Url.Action("Details", "Product", new { id = product.ProductId })" class="btn btn-secondary btn-sm">
                <i class="fas fa-arrow-left"></i> Ürün Detayına Dön
            </a>
            <a href="@Url.Action("Create", "StockMovement")" class="btn btn-primary btn-sm">
                <i class="fas fa-plus"></i> Yeni Stok Hareketi
            </a>
        </div>
    </div>
    <div class="card-body">
        <div class="row mb-4">
            <div class="col-md-3">
                <div class="card bg-info text-white">
                    <div class="card-body">
                        <h5 class="card-title">Mevcut Stok</h5>
                        <h2>@product.Stock</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card bg-warning text-white">
                    <div class="card-body">
                        <h5 class="card-title">Minimum Stok</h5>
                        <h2>@product.MinimumStock</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card bg-success text-white">
                    <div class="card-body">
                        <h5 class="card-title">Alış Fiyatı</h5>
                        <h2>@string.Format("{0:C2}", product.PurchasePrice)</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card bg-primary text-white">
                    <div class="card-body">
                        <h5 class="card-title">Satış Fiyatı</h5>
                        <h2>@string.Format("{0:C2}", product.SalePrice)</h2>
                    </div>
                </div>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-light">
                        <h5 class="card-title">Ürün Bilgileri</h5>
                    </div>
                    <div class="card-body">
                        <p><strong>Kategori:</strong> @product.Category.CategoryName</p>
                        <p><strong>Tedarikçi:</strong> @product.Supplier.CompanyName</p>
                        <p><strong>Barkod:</strong> @(string.IsNullOrEmpty(product.Barcode) ? "-" : product.Barcode)</p>
                        <p><strong>Marka:</strong> @(string.IsNullOrEmpty(product.Brand) ? "-" : product.Brand)</p>
                        <p><strong>Son Alım Tarihi:</strong> @(product.LastPurchaseDate.HasValue ? product.LastPurchaseDate.Value.ToString("dd/MM/yyyy") : "-")</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-light">
                        <h5 class="card-title">Stok Özeti</h5>
                    </div>
                    <div class="card-body">
                        <p><strong>Toplam Giriş:</strong> @Model.Where(m => m.MovementType == "Giriş").Sum(m => m.Quantity)</p>
                        <p><strong>Toplam Çıkış:</strong> @Model.Where(m => m.MovementType == "Çıkış").Sum(m => m.Quantity)</p>
                        <p><strong>Toplam Satış:</strong> @Model.Where(m => m.MovementType == "Satış").Sum(m => m.Quantity)</p>
                        <p><strong>Toplam İade:</strong> @Model.Where(m => m.MovementType == "İade").Sum(m => m.Quantity)</p>
                        <p><strong>Toplam Hareket Sayısı:</strong> @Model.Count()</p>
                    </div>
                </div>
            </div>
        </div>

        <h4 class="mt-4">Stok Hareketleri</h4>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Hareket Tipi</th>
                    <th>Miktar</th>
                    <th>Birim Fiyat</th>
                    <th>Çalışan</th>
                    <th>Tarih</th>
                    <th>Açıklama</th>
                    <th>İşlemler</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.OrderByDescending(m => m.MovementDate))
                {
                    <tr>
                        <td>
                            @if (item.MovementType == "Giriş")
                            {
                                <span class="badge bg-success">@item.MovementType</span>
                            }
                            else if (item.MovementType == "Çıkış")
                            {
                                <span class="badge bg-danger">@item.MovementType</span>
                            }
                            else if (item.MovementType == "Sayım")
                            {
                                <span class="badge bg-info">@item.MovementType</span>
                            }
                            else if (item.MovementType == "Satış")
                            {
                                <span class="badge bg-primary">@item.MovementType</span>
                            }
                            else if (item.MovementType == "İade")
                            {
                                <span class="badge bg-warning">@item.MovementType</span>
                            }
                            else
                            {
                                <span class="badge bg-secondary">@item.MovementType</span>
                            }
                        </td>
                        <td>@item.Quantity</td>
                        <td>@(item.UnitPrice.HasValue ? string.Format("{0:C2}", item.UnitPrice) : "-")</td>
                        <td>@($"{item.Employee.FirstName} {item.Employee.LastName}")</td>
                        <td>@item.MovementDate.ToString("dd/MM/yyyy HH:mm")</td>
                        <td>@(string.IsNullOrEmpty(item.Description) ? "-" : item.Description)</td>
                        <td>
                            <a href="@Url.Action("Details", "StockMovement", new { id = item.StockMovementId })" class="btn btn-primary btn-sm">
                                <i class="fas fa-search"></i> Detay
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div> 